server:
  port: 80
spring:
  application:
    name: cloud-consumer-service

eureka:
  client:
    register-with-eureka: true #表示是否将自己注册进EurekaServer，默认为true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true